name: Deploy Frontend business.dynomenu.com
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          check-latest: true
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: npm run generate
      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            echo "Remove existing files"
            rm -rf apps/frontend-business
      - uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          source: 'dist/*'
          target: "apps/frontend-business"
          strip_components: 1